### ISSUE TITLE
Alarm by aux command..

### ISSUE THREAD

**Issue by umbz** [mvalla/openhab2-addons#32] opened 2018-12-12 06:55 UTC
hi mvalla again , 
will it be in the roadmap controlling burglar alarm (34686) by aux commands ?

**Comment by umbz** [comment] 2018-12-12 06:56
#12

**Comment by umbz** [comment] 2018-12-12 06:56
https://www.domoticz.com/forum/viewtopic.php?t=14053&start=40

**Comment by mvalla** [comment] 2019-01-07 17:16
I think this is a duplicate of #12, correct?
If yes, I will close this as duplicate.

**Comment by Gozilla01** [comment] 2019-01-07 17:48
I suppose it's the same thing, but I have no Bticino alarm

**Comment by Gozilla01** [comment] 2019-02-23 22:03
See pull request [58](https://github.com/mvalla/openhab2-addons/pull/58)

**Comment by Gozilla01** [comment] 2019-03-23 08:48
Remove label question

**Comment by mvalla** [comment] 2019-10-06 15:58
Close this as duplicate of #12

**Closed by mvalla** 2019-10-06 15:58 UTC
Labels: duplicate, newWHO, question
