### ISSUE TITLE
CEN-CEN+ thing disappears

### ISSUE THREAD

**Issue by Gozilla01** [mvalla/openhab2-addons#38] opened 2018-12-31 05:53 UTC
@bastler [https://community.openhab.org/t/bticino-openwebnet-adding-cen-commands-design/54142/74](url)
Beta9-1
very often if i change something in my things-file, the entry disappears in paperui/things. i have to give a new name then thing is back again

**Comment by Gozilla01** [comment] 2018-12-31 05:54
@bastler
Does the log show some error when it happens that the CEN thing disappears ?

**Comment by Gozilla01** [comment] 2018-12-31 05:55
In the beta9 version the same problem happened with CEN +

**Comment by mvalla** [comment] 2019-01-07 18:22
Do you have devices/things with the same WHERE ?
For example: light with A=3, PL=4 -> WHERE=34 and CEN+ with Id=4 -> WHERE=34

**Comment by julesbike** [comment] 2019-03-01 14:29
I am getting the same error and yes this is where I have matchinng WHERE - so I have a light Actuator which is A=2  P=3 and  CEN+ which is CEN=3 but because Openwebnet adds a 2 it is discovered as Where = 23.   I have some CEN+ which have a 2 digit number eg: 36 and these are fine because they appear as Where = 236

**Comment by Gozilla01** [comment] 2019-03-01 15:17
@julesbike 
Are you sure you're using the **bus_cenplus_scenario_control**?
Post the file or a picture of the things

**Comment by mvalla** [comment] 2019-03-02 05:51
if this was caused by this issue #42 (causing not correct handling of things with matching WHERE), it was corrected already in version beta9-2.
If with newer versions of the binding this issue here does not show anymore, I will close it.

**Comment by Gozilla01** [comment] 2019-03-02 07:18
Issue #38 is still a problem, see post I sent you.

**Comment by julesbike** [comment] 2019-03-02 09:58
@Gozilla01  unfortunately I have not got the logs for the error and I have changed everything so I can't reproduce the error.   I am using the following binding - which I think is the latest??

`191 │ Active   │  80 │ 2.4.0.201812132158     │ OpenWebNet Binding`

**Comment by mvalla** [comment] 2019-03-02 11:20
@julesbike Since from the timestamp you using binding version 2.4.0-b9 (3 versions ago!) you should update the binding to the lastest version and try again.
@Gozilla01 I will look to the simulation, but I also think there are some issues with OH2 (cache?) about refreshing things, and these issues may be have been fixed in OH2.5.0

**Comment by Gozilla01** [comment] 2019-03-02 11:34
I tried a week ago to install OH2.5.0, but too many problems and I returned to 2.4

**Comment by mvalla** [comment] 2019-03-23 21:48
I will close this issue if no other user report this to happen again with latest binding version (2.5.0.M2-1)

**Comment by mvalla** [comment] 2019-04-07 08:02
since this is issue appears to be not replicable and is not happening in 2.5.0, it is closed for now

**Closed by mvalla** 2019-04-07 08:02 UTC
Labels: invalid, question
