### ISSUE TITLE
AUX

### ISSUE THREAD

**Issue by gabrieledaltoe** [mvalla/openhab2-addons#87] opened 2019-08-18 11:50 UTC
Ciao Massimo.
There are news about AUX support ? Thanks

**Comment by fmalfatto** [comment] 2019-08-21 10:20
I'm following this request too, but I'm quite sure that AUX is not supported by MHS1. I just tried it in Domoticz and MHS1 does not act as gw for AUX commands to 3486. BTicino ufficial support says that only 454 gw is fully supporting.

**Comment by mvalla** [comment] 2019-09-06 10:22
is this a duplicate of #12 ? It looks so. If correct I will close this as duplicate.

**Comment by mvalla** [comment] 2019-10-06 15:43
closed as it appears as duplicate of #12

**Closed by mvalla** 2019-10-06 15:43 UTC
Labels: duplicate, newWHO, question
