### ISSUE TITLE
Discovering automation things with MyHomeServer1

### ISSUE THREAD

**Issue by Jeby057** [mvalla/openhab2-addons#34] opened 2018-12-22 17:11 UTC
Hi,

First of all, thank you for your work !
This project is really cool !

About my gateway, I have a MyHomeServer1.
My web-server is perfectly recognized by OpenHab (installed on DSM) and I can find any on/off switch of my installation.
However, I have some issues to discover dimmer and automation things.

About the dimmer things, I found a workaround : I need to turn on the light. If the light is off, I can't find it.

About the automation things, I have some errors in the log file : 
[...]
2018-12-22 17:39:51.864 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*033##
[...]

And when I create manually an automation thing with WHERE=033 (for example), I have an UNKNOWN state.

I hope that this can help you to improve this project.
Don't hesitate to contact me if you have questions or to test new versions.

**Comment by mvalla** [comment] 2018-12-22 18:49
As clearly explained in the README, dimmers are found as dimmers only if they are ON and dimmed.
Otherwise in any case they should be found as normal switches.
If they are not found at all, then I need more information. 
Delete the dimmers you have configured, set log level to DEBUG (see [README](https://github.com/mvalla/openhab2-addons/tree/openwebnet/addons/binding/org.openhab.binding.openwebnet) how) and start a new discovery from Inbox, then send me your openhab.log file (better send it using PM in the openHAB [community](https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/360)).

Regarding the Automation not discovered, same info is needed:
- openHAB & binding version installed
- log set to DEBUG
- openhab.log file just after a new discovery has been tested 
The log line you posted here has not been put under "code fences" so is not useful, and more log is needed at DEBUG level to understand what is going on with your Automation device.

bye
M

**Comment by mvalla** [comment] 2018-12-22 21:38
something strange is going on here:
messages like: 
`2018-12-22 20:17:12.974 [INFO ] [g.openwebnet.bus.MyHomeSocketFactory] - COM RECEIVED  <<<<<<<<<<<<============ *2*033##`
are invalid in the OpenWebNet protocol (`*2*033##` is an invalid frame!!!), so is very unlikely that the MyHomeServer1 sends these messages back as answers to the binding.
So something is still not showing correctly in your log.

- Download this official client from BTicino: 
https://www.myopen-legrandgroup.com/developers/  >> tab TOOLS >> download and run **OpenWebNet Client - Windows** (exec file is `OpenWebNet_Client.exe`).
- put the IP address of your MyHomeServer1 and its password (select HMAC if password has characters and not just numbers).
- write `*#2*0##` in the Frame box, click `Send`

Then send here a picture of the result.
bye
M

**Comment by fmalfatto** [comment] 2018-12-23 07:48
Same for me! 
![cattura](https://user-images.githubusercontent.com/7314962/50381770-8dc37e00-068f-11e9-9cf1-dd722730501f.JPG)

**Comment by mvalla** [comment] 2018-12-23 08:00
Ok very interesting. 
So we have 2 gateways that send invalid OpenWebNet frames answers!!
BTicino products are full of surprises!

Which versions of MyHOMEServer1 firmware do you have?

Can you do the same test here with this command:
`*#1*0#`
I want to see if this command can discover both lights (`*1*what*where##`) and automations (`*2*what*where##`) and if automation answers have valid frames this time...

**Comment by fmalfatto** [comment] 2018-12-23 08:50
My HomeServer1 is at 2.2.11 .
I have another gateway (3.5 touch) and it gives the same answer to message *#2*0##

Here is the *#1*0##    command (missing a # in your post):
![cattura](https://user-images.githubusercontent.com/7314962/50382104-2100b180-0698-11e9-8f45-77fe85d0ea24.JPG)

**Comment by mvalla** [comment] 2018-12-23 09:16
Ok @fmalfatto
I imagine you also cannot find automatically from PaperUI inbox the automations devices in your system, right?
Can you configure them manually via PaperUI?

What answer the OWN client gives to this command:
`*#2*031##` ?

**Comment by Jeby057** [comment] 2018-12-23 10:15
Hi,

I have the last version of the firmware (2.2.14).

Here the results of *#1*0## command : 
![capture1](https://user-images.githubusercontent.com/2663365/50382609-e3098a80-06a3-11e9-9bec-e99e82305a1d.PNG)
![capture2](https://user-images.githubusercontent.com/2663365/50382610-e6047b00-06a3-11e9-9ecd-28aa9e73ca68.PNG)

**Comment by mvalla** [comment] 2018-12-23 16:14
Sorry @fmalfatto but I cannot understand from your description  if using the PaperUI Inbox scan you can find all your 4 automation devices or not.
Can you post an image of the scan result from PaperUI?
Also can you post here the configuration line you use in .things file for the rollershutter with WHERE=031 ??

You have the same MyHOMEServer1 gateway as @Jeby057 but he cannot find his rollershutter and you say you have found all your devices.

Also the answers  both of you  have from the automation discovery request (`*#2*0##`) are completely non-sense to me because they brake the basic formatting rules off OpenWebNet messages according to their official documentation.

Massi
[IMPORTANT **always use code fences when posting OWN frames**otherwise the web page will modify them and cut characters form them !!]

**Comment by Jeby057** [comment] 2018-12-23 16:33
You said that the response of the gateway are non-sense. But usually what should be the answer of this request ? Maybe it's due to a recent update of Bticino. It's strange that they don't follow the official documentation. Have you an idea to do a workaround ? 
Thanks

**Comment by fmalfatto** [comment] 2018-12-23 16:40
Sorry for my poor english. I realize I confused your ideas! I try to explain:
1) PaperUi never found the 4 automation devices. I installed them after I began to configure everything manually and never rescan devices again until today. And neither today it found automation devices. It listed all switches and thermostats also if they are all  alredy defined in files. 

2) things file for the first rollershutter:         
bus_automation   Studio_F               "T. Studio F."                  [ where="31", shutterRun="40000" ]

3) items file:
Rollershutter Tenda_St_F "T. Fulvio [%d %%]"  <blinds> (Tende) { channel="openwebnet:bus_automation:mhs1:Studio_F:shutter"}

With these configuration files I found things in Paper UI :
![cattura](https://user-images.githubusercontent.com/7314962/50385702-dacc4200-06d9-11e9-8de5-95e88bb81d13.JPG)

**Comment by fmalfatto** [comment] 2018-12-23 16:55
This is the log of the scan done by PaperUI:
2018-12-23 17:35:41.206 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:11' to inbox.
2018-12-23 17:35:41.233 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:21' to inbox.
2018-12-23 17:35:41.255 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:12' to inbox.
2018-12-23 17:35:41.276 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:22' to inbox.
2018-12-23 17:35:41.291 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:13' to inbox.
2018-12-23 17:35:41.299 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:23' to inbox.
2018-12-23 17:35:41.310 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:14' to inbox.
2018-12-23 17:35:41.319 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:24' to inbox.
2018-12-23 17:35:41.331 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:03' to inbox.
2018-12-23 17:35:41.341 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:02' to inbox.
2018-12-23 17:35:41.350 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:15' to inbox.
2018-12-23 17:35:41.359 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:25' to inbox.
2018-12-23 17:35:41.367 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:06' to inbox.
2018-12-23 17:35:41.379 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:09' to inbox.
2018-12-23 17:35:41.386 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:05' to inbox.
2018-12-23 17:35:41.397 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:08' to inbox.
2018-12-23 17:35:41.407 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:04' to inbox.
2018-12-23 17:35:41.416 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:07' to inbox.
2018-12-23 17:35:41.425 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:0010' to inbox.
2018-12-23 17:35:41.435 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_on_off_switch:mhs1:01' to inbox.
2018-12-23 17:35:43.869 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*031##
2018-12-23 17:35:43.872 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*032##
2018-12-23 17:35:43.873 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*033##
2018-12-23 17:35:43.875 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*034##
2018-12-23 17:35:50.396 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_thermostat:mhs1:1' to inbox.
2018-12-23 17:35:50.410 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'openwebnet:bus_thermostat:mhs1:2' to inbox.

In my opinion the server should aswer [*2*0*31##] instead of [*2*031##] because I have four devices on automation bus, numbered from 31 to 34.

**Comment by mvalla** [comment] 2018-12-23 20:02
> You said that the response of the gateway are non-sense. But usually what should be the answer of this request ? Maybe it's due to a recent update of Bticino. It's strange that they don't follow the official documentation. Have you an idea to do a workaround ?

> In my opinion the server should answer `*2*0*31##` instead of `*2*031##` because I have four devices on automation bus, numbered from 31 to 34.

**Exactly**: the answer to the "get status" command for Automation: `*#2*0##` should be a list of commands with the status for each automation device: for example: `*2*0*31##`  for WHERE=31.

Receiving `*2*031##`  **makes no sense to me** and is against the official BTicino documentation, but this happens both with the binding and the official OWN client. Which is absurd, because I have many other users with MyHOMEServer1 who had no problems with finding automation devices in their system.

So I will keep this issue open and ask more information elsewhere.

The workaround is clear but very very ugly: to accept these not valid answers from MyHOMEServer1 (maybe just for this model of gateway and for some specific firmware versions).. just to fix a ugly bug by BTicino.

**Comment by Jeby057** [comment] 2018-12-23 20:32
After some research about OpenWebNet language and some tests, I think you are right.
It's very strange... Why the * is missing in the answer... Maybe a bug directly in the firmware. 

Surprise !!! It works now when I configure it manually. Before it had the state "UNKNOWN" or "PENDING...".

However I have a lot of bugs in the log file when I use it.

When I go down the shutter : 

```
2018-12-23 21:21:15.270 [DEBUG] [ebnet.handler.OpenWebNetThingHandler] - ==OWN:ThingHandler== handleCommand() (command=UP - channel=openwebnet:bus_automation:10bc4436:shutter)
2018-12-23 21:21:15.271 [INFO ] [g.openwebnet.bus.MyHomeJavaConnector] - COM SENDING   ============>>>>>>>>>>>> *2*1*31##
2018-12-23 21:21:15.271 [DEBUG] [g.openwebnet.bus.MyHomeSocketFactory] - ##gw-openwebnet-socket## CANNOT read from socket: read returned -1
2018-12-23 21:21:15.273 [DEBUG] [g.openwebnet.bus.MyHomeJavaConnector] - ##gw-openwebnet-connector## read returned -1
2018-12-23 21:21:15.274 [DEBUG] [g.openwebnet.bus.MyHomeJavaConnector] - ##gw-openwebnet-connector## let's try with a NEW SESSION...
2018-12-23 21:21:15.274 [INFO ] [g.openwebnet.bus.MyHomeSocketFactory] - ##gw-openwebnet-socket## Trying openCommandSession() socket....  (192.168.178.28:20000)
2018-12-23 21:21:15.276 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - ##gw-openwebnet-conn## ... starting HANDSHAKE ...
2018-12-23 21:21:15.277 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM RECEIVED   <<<<<<====== *#*1##
2018-12-23 21:21:15.277 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM SENDING    ======>>>>>> *99*0##
2018-12-23 21:21:15.279 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM RECEIVED   <<<<<<====== *98*2##
2018-12-23 21:21:15.280 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM SENDING    ======>>>>>> *#*1##
2018-12-23 21:21:15.282 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM RECEIVED   <<<<<<====== *#11150812061409070911000309100712140503091013031413081302041304150606150212040710111111030405071312051412030912020901021306090208##
2018-12-23 21:21:15.283 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM SENDING    ======>>>>>> *#02140808101306061310121211041308151500071208071212050501031401150006051502090310020101070104150901070112110211150004040010111000*02060003000607090709151508080003020412090302070409111514091414141509140401090804080110110503061211110315131506080405051301060014##
2018-12-23 21:21:15.285 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM RECEIVED   <<<<<<====== *#08140508121501101004020405111002060305141408040200061311130307041403050210070200020304150405040001081212031407100010031001090907##
2018-12-23 21:21:15.285 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - COM SENDING    ======>>>>>> *#*1##
2018-12-23 21:21:15.286 [INFO ] [g.openwebnet.bus.MyHomeSocketFactory] - ##gw-openwebnet-socket## ... CONNECTED command session 192.168.178.28:20000
2018-12-23 21:21:15.287 [INFO ] [g.openwebnet.bus.MyHomeJavaConnector] - COM SENDING   ============>>>>>>>>>>>> *2*1*31##
2018-12-23 21:21:15.374 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*1000#0*31##
2018-12-23 21:21:15.374 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*1000#0*31## exception: java.lang.IllegalArgumentException: unsupported WHAT for frame: 1000#0
2018-12-23 21:21:15.374 [DEBUG] [org.openwebnet.OpenGatewayBus       ] - ##gw-openwebnet-BUS## Malformed/Unsupported OpenMessage: *2*1000#0*31##
2018-12-23 21:21:15.399 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*0*31##
2018-12-23 21:21:15.400 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # [[[ internalState=0 positionEst=-1 - calibrating=-1 shutterRun=-1 ]]]
2018-12-23 21:21:15.432 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*1000#1*31##
2018-12-23 21:21:15.432 [INFO ] [g.openwebnet.bus.MyHomeSocketFactory] - COM RECEIVED  <<<<<<<<<<<<============ *#*1##
2018-12-23 21:21:15.432 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*1000#1*31## exception: java.lang.IllegalArgumentException: unsupported WHAT for frame: 1000#1
2018-12-23 21:21:15.433 [DEBUG] [org.openwebnet.OpenGatewayBus       ] - ##gw-openwebnet-BUS## Malformed/Unsupported OpenMessage: *2*1000#1*31##
2018-12-23 21:21:15.459 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*1*31##
2018-12-23 21:21:15.460 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # MOVING 1 - startedMovingAt=1545596475460 - 15.460
2018-12-23 21:21:15.461 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # [[[ internalState=1 positionEst=-1 - calibrating=-1 shutterRun=-1 ]]]

```

When I go down the shutter : 
```
2018-12-23 21:21:34.903 [DEBUG] [ebnet.handler.OpenWebNetThingHandler] - ==OWN:ThingHandler== handleCommand() (command=STOP - channel=openwebnet:bus_automation:10bc4436:shutter)
2018-12-23 21:21:34.903 [INFO ] [g.openwebnet.bus.MyHomeJavaConnector] - COM SENDING   ============>>>>>>>>>>>> *2*0*31##
2018-12-23 21:21:34.955 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*1000#0*31##
2018-12-23 21:21:34.956 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*1000#0*31## exception: java.lang.IllegalArgumentException: unsupported WHAT for frame: 1000#0
2018-12-23 21:21:34.956 [DEBUG] [org.openwebnet.OpenGatewayBus       ] - ##gw-openwebnet-BUS## Malformed/Unsupported OpenMessage: *2*1000#0*31##
2018-12-23 21:21:34.957 [INFO ] [g.openwebnet.bus.MyHomeSocketFactory] - COM RECEIVED  <<<<<<<<<<<<============ *#*1##
2018-12-23 21:21:34.977 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*0*31##
2018-12-23 21:21:34.979 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # [[[ internalState=0 positionEst=-1 - calibrating=-1 shutterRun=-1 ]]]
2018-12-23 21:21:40.264 [DEBUG] [ebnet.handler.OpenWebNetThingHandler] - ==OWN:ThingHandler== handleCommand() (command=DOWN - channel=openwebnet:bus_automation:10bc4436:shutter)
2018-12-23 21:21:40.264 [INFO ] [g.openwebnet.bus.MyHomeJavaConnector] - COM SENDING   ============>>>>>>>>>>>> *2*2*31##
2018-12-23 21:21:40.300 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*1000#0*31##
2018-12-23 21:21:40.301 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*1000#0*31## exception: java.lang.IllegalArgumentException: unsupported WHAT for frame: 1000#0
2018-12-23 21:21:40.301 [DEBUG] [org.openwebnet.OpenGatewayBus       ] - ##gw-openwebnet-BUS## Malformed/Unsupported OpenMessage: *2*1000#0*31##
2018-12-23 21:21:40.328 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*0*31##
2018-12-23 21:21:40.329 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # [[[ internalState=0 positionEst=-1 - calibrating=-1 shutterRun=-1 ]]]
2018-12-23 21:21:40.361 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*1000#2*31##
2018-12-23 21:21:40.362 [ERROR] [penwebnet.message.OpenMessageFactory] - ##openwebnet## INVALID FRAME: *2*1000#2*31## exception: java.lang.IllegalArgumentException: unsupported WHAT for frame: 1000#2
2018-12-23 21:21:40.362 [DEBUG] [org.openwebnet.OpenGatewayBus       ] - ##gw-openwebnet-BUS## Malformed/Unsupported OpenMessage: *2*1000#2*31##
2018-12-23 21:21:40.362 [INFO ] [g.openwebnet.bus.MyHomeSocketFactory] - COM RECEIVED  <<<<<<<<<<<<============ *#*1##
2018-12-23 21:21:40.389 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*2*31##
2018-12-23 21:21:40.390 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # MOVING 2 - startedMovingAt=1545596500390 - 40.390
2018-12-23 21:21:40.391 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # [[[ internalState=2 positionEst=-1 - calibrating=-1 shutterRun=-1 ]]]
```

**Comment by mvalla** [comment] 2018-12-23 21:58
> However I have a lot of bugs in the log file when I use it.
`##openwebnet## INVALID FRAME: *2*1000#0*31## exception: java.lang.IllegalArgumentException: unsupported WHAT for frame: 1000#0`

This is already reported in issue #29 , an will be supported in beta9 when released.

Regarding the automation working, from the logs it looks like the UP/DOWN commands sent to the BUS are confirmed.
For example this Down command: `*2*2*31##` to automation device 31 has been confirmed going down from the BUS in the following MONitor message `*2*2*31##`:
`21:21:40.264 [INFO ] [g.openwebnet.bus.MyHomeJavaConnector] - COM SENDING   ============>>>>>>>>>>>> *2*2*31##`
...
`21:21:40.389 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *2*2*31##`
`21:21:40.390 [DEBUG] [.handler.OpenWebNetAutomationHandler] - ==OWN:AutomationHandler== # 31 # MOVING 2 - startedMovingAt=1545596500390 - 40.390`
So where is the problem?

**Comment by Jeby057** [comment] 2018-12-24 09:32
Ok for the release 9. 

About the another problem, it's my mistake.  I have a lot of shutters :-) 
So, if we configure manually, it works fine.

Thanks.

**Comment by fmalfatto** [comment] 2018-12-28 17:45
I wrote to BTicino about the invalid frames returned from automation bus. They only answered that MHS1 is not an official gateway:
`Gentile cliente, in merito alla sua richiesta, siamo ad informarla che il prodotto MyHomeserver1 non viene dichiarato con la funzionalità di gateway.Pertanto tutte le funzionalità di invio/ricezione/traduzione codici OPEN non viene garantita.
Per integrazioni con terze parti siamo a consigliarLe di installare il webserver art. F454 o il driver manager art. `
I would expect a not supported message or an error, not a wrong frame :-)
I have another unsupported gw and I will try to see if it gives the same problem.

**Comment by fmalfatto** [comment] 2018-12-29 09:44
I can confirm that the invalid frames received as answer to the "get status" command for Automation: *#2*0## is a problem coming from the MHS1.
I changed my gateway using the  touch 3.5 LN4890 (ufficially unsupported) and the messages about wrong frames are gone. 
PaperUi discovers all my blinds:
![cattura](https://user-images.githubusercontent.com/7314962/50536628-aaabf580-0b56-11e9-9c2d-6b35bb0475e8.JPG)

Now I try to keep in test the LN4890 as gateway (I did not change the name for mhs1 in things file so I have the save devices as before):
`// Bridge openwebnet:bus_gateway:mhs1 [ host="192.168.1.40", passwd="" ] {
// test gw touch 3.5 LN4890
Bridge openwebnet:bus_gateway:mhs1 [ host="192.168.1.50", passwd="" ] {
`

**Comment by mvalla** [comment] 2019-01-07 17:18
Ok since the problem is with the MHS1 gateway, this will not be fixed in the binding. I will leave this issue open to track if the problem is solved in future firmware versions.

**Comment by mvalla** [comment] 2019-05-21 08:49
@fmalfatto is this issue still valid or has it been corrected by BTicino?

**Comment by fmalfatto** [comment] 2019-05-21 09:24
I tested today after the new firmware on MHS1 and it looks as fixed:
![Cattura](https://user-images.githubusercontent.com/7314962/58084266-d5a4ed80-7bba-11e9-80a5-07ed768a2f23.JPG)

**Comment by mvalla** [comment] 2019-05-21 09:55
ok, than this issue can be closed

**Closed by mvalla** 2019-05-21 09:55 UTC
Labels: wontfix
