### ISSUE TITLE
Request: push button function

### ISSUE THREAD

**Issue by nix1986** [mvalla/openhab2-addons#90] opened 2019-08-29 13:11 UTC
Salve, attualmente sul mio impianto ho diversi tasti che usano la funzione PUL per gestire il carico connesso sull'attuatore e quindi molte funzioni non possono essere portate su openhab.

Volevo chiederti se è possibile aggiungere la funzione pulsante in una delle prossime relase e avere la possibilità di inserire una stringa openwebnet personalizzata es. elettroserratura *6 *10 *4000##

Grazie
Max

**Comment by mvalla** [comment] 2019-09-06 10:37
issues must be formulated in English.

- For the PUL function: can you explain better - with examples of OpenWebNet messages - which kind of messages you would like to be supported?

- Support for generic messages like `*6 *10 *4000##` is already described in #65

**Comment by nix1986** [comment] 2019-09-06 12:21
Sorry for Italian my English is not very good :)

PUL mode (contact is set to normal open)

The openwebnet message sent is:

```
pressed = ON
*1*1000#1*1003##
*1*1*1003##

relased = OFF
*1*1000#0*1003##
*1*0*1003##

```
The difference between switch mode and pul mode is an another message sent before the standard on/off message which recall the "where 1003" in my case.

![PUL CODE](https://user-images.githubusercontent.com/54669058/64427314-3fd19780-d0b1-11e9-9a57-ed1b8c837d3e.jpg)

**Comment by mvalla** [comment] 2019-09-06 14:51
ok, I will check what the binding does if receives these messages.
change title and description. google translate works well.......

**Comment by mvalla** [comment] 2019-09-06 16:27
i do not understand the requirement. 
the binding already handles correctly messages like `*1*1000#1*1003##` by swithcing the light on (or OFF in the case of WHAT=1000#0.
Can you explain what you want to achieve, the expected behavior and what is not working in your case?

**Comment by nix1986** [comment] 2019-09-06 17:51
I have these version of binding, i think is the last relased bindings
![binding version](https://user-images.githubusercontent.com/54669058/64446746-e6319300-d0d9-11e9-8d49-51204f2ec4a4.jpg)

I have some dimming ballast which work in push button mode (not a dali dimmer)
push button mode function is resumed in: pressed  one time = light ON ; button long pressed = dimming function ; pressed one more time = OFF
the push button work: pressed= contact close ; relased= contact open
your switch work: pressed= contact close, pressed one more time= contact open
The contact in the actuator reproduced the pressed and relased push button
When i relased the push button the contact in the actuator is open (OFF)
The contact in the actuator is closed only if the push button is pressed but when relased the contact is open.

push button or PUL function is not same a switch function.

![item configuration](https://user-images.githubusercontent.com/54669058/64448880-f39d4c00-d0de-11e9-93a1-243a81bfd092.jpg)
adding push button function in this list is a good things, maybe the function is possible to setting in this command:

pressed send a on command,relased send a off command to the actuator

**Comment by mvalla** [comment] 2019-10-06 14:55
> adding push button function in "Type" is a good things

a Push button Type does not exists in openHAB, therefore  you have to use other methods to achieve your goals.

For example see here: https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/862
You need to install the Expire binding and configure your switch item like in the example, this way you can simulate : pressed = contact closed (ON), released = contact open (send OFF)

For dimming I cannot see an easy way to use dimming connected to your PUL button.
Maybe with the help of a Dimmer item (that has value 0%-100%) and then a rule that takes the % value form the dimmer item when it changes, sends a ON (pressed) commands to the switch and after time to be proportional to the item %, send a OFF (released) command.
It's just a suggestion to try and test, not sure it will work well.

**Comment by mvalla** [comment] 2019-10-06 15:29
Since the push button function is not related to the binding but needs to be simulated in OH using Expire binding and rules,
and since support for generic messages is already described in #52, I will close this issue as duplicate and invalid.

**Closed by mvalla** 2019-10-06 15:29 UTC
Labels: duplicate, invalid, question
